### ISSUE TITLE
Calling from C++: Linker errors due to missing KDTREE_API

### ISSUE THREAD

**Issue by DashW** [nutti/UEPlugin-Kdtree#4]
All publicly accessible classes should be marked with KDTREE_API to mark their methods as EXTERN and prevent other modules from attempting to link against them statically. 

e.g. the UkdtreeBPLibrary should be declared:
`class KDTREE_API UKdtreeBPLibrary`

This will fix "**unresolved external symbol**" linker errors when attempting to call those functions directly from C++ in another module. 

These errors have not been observed in the past because the module is designed to be called from non-nativized blueprint, which only links dynamically, never statically. However, these issues may start to appear if calling blueprints are added to the nativization list!

**Comment by nutti** [comment]
@DashW 

Thanks for your great feedback!
I did not know about that.
I will fix it ASAP.

**Comment by nutti** [comment]
Fixed this issue.
