### ISSUE TITLE
CollectFromKdtree Returns Incorrect Position Data

### ISSUE THREAD

**Issue by DashW** [nutti/UEPlugin-Kdtree#5]
KdtreeBPLibrary.cpp, Line 29:
`Data.Add(Tree.Internal.Data[Index]);`
will return only the first n vertices from the vertex buffer, not the matched vertices from the search.
The line should be:
`Data.Add(Tree.Internal.Data[Indices[Index]]);`

**Comment by nutti** [comment]
@DashW 

Nice catch! Thanks!
I will fix ASAP.

BTW, if you are interested in fixing this bug, you can send me the pull request same as #3 .
This project is contribution welcome.
What do you think? (Same #4 as well)

Anyway, thanks so much to give me your feedback!

**Comment by nutti** [comment]
Fixed this issue.
