### ISSUE TITLE
How to return index of input locations that matched?

### ISSUE THREAD

**Issue by Sivx** [nutti/UEPlugin-Kdtree#6]
Hello,
I would like to store meta data about positions in a game.  How would I go about returning the results as an index of the original array? Or what would you recommend going about storing meta data for a particular position in an efficient manner?
Thanks,
Dan

**Comment by nutti** [comment]
The returned index is the index of input array.
So you can use the returned index for accessing to input array as long as the input array is remained as original.

**Comment by Sivx** [comment]
Woops, sorry about that. Thanks for your hard work!

**Comment by nutti** [comment]
I will close this issue because the issue seems to be solved.
